### ISSUE TITLE
Add to GRDI-AMR.com

### ISSUE THREAD

**Issue by chapb** [superphy/AMR_Predictor#4]
Was development related to the GRDI-AMR1 or GRDI-AMR2 projects?

If so, would you mind if I linked to this project from https://grdi-amr.com?

**Comment by RylanSteinkey** [comment]
It was GRDI-AMR1.

But you should add https://github.com/superphy/acheron instead, as it is more up to date and has a wiki.

**Comment by chapb** [comment]
Thanks!
